server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    password: Patrick12345!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
