server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id : ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id : PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

okta:
  oauth2:
    issuer: https://dev-12058945.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa7t3yvr7KQ6pJ0Q5d7
    client-secret: ESNn7UOAy-ct6pAQ-PLR_Wyd6_JJMMYIxa9m84gq
    scopes: openid, email, profile, offline_access

#okta:
#  oauth2:
#    issuer: https://dev-31074102.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oa7t3l9w0PCzDxsG5d7
#    client-secret: kbFlPr0-H4dqrbvV8iOath457Wg68Sp3hMG4J1I3
#    scopes: openid, email, profile, offline_access